### ISSUE TITLE
Shiro Middleware Based on jCasbin

### ISSUE THREAD

**Issue by soberich** [jcasbin/shiro-casbin#1]
Hi,
What is the status and plan?

**Comment by hsluoyz** [comment]
Hi, we are collecting ideas about Shiro's plugin. In fact, we found it's also OK for Shiro users to directly shift to use jCasbin instead. As a Shiro user, what's your concern and focus for this project? I'd like to hear. Thanks.

**Comment by hsluoyz** [comment]
We want to have some progress on this one. @fangzhengjin @kingiw @DivyPatel9881 @hackerchai

**Comment by sanyue-dev** [comment]
Jcasbin How to replace shiro

**Comment by hsluoyz** [comment]
@tldyl

**Comment by shy1st** [comment]
@hsluoyz @fangzhengjin
In version 0.0.1, maybe we can try to use RBAC & ABAC authorization on jcasin to replace the authorization on Shiro by writing the "if/else" authorization code or using annotations.We can try to get the current login user, and then use jcasin to judge whether the user has the specified permissions.What is your opinion?

**Comment by hsluoyz** [comment]
@shy1st great! I think it sounds reasonable for v0.0.1

**Comment by shy1st** [comment]
@hsluoyz OK,I will try to do that.
