### ISSUE TITLE
Code coverage is still down

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/shiro-casbin#14]
See: https://coveralls.io/github/jcasbin/shiro-casbin?branch=master

**Comment by shy1st** [comment]
@hsluoyz I have fixed the code coverage, please see:
![QQ图片20210214125145](https://user-images.githubusercontent.com/34126552/107868922-812fbe80-6ec3-11eb-9189-721ea3f1e752.png)

**Comment by hsluoyz** [comment]
Great!
